# -*- coding: utf-8 -*-
"""google street view_可以篩選年份！

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YKojmCzplROkUmQ0o-AlKD9OXKaEi6hi

# Connect to google drive
"""

from google.colab import drive
drive.mount('/content/drive')

cd /content/

"""# Downlaod library """

pip install git+https://github.com/robolyst/streetview

pip install streetview

"""# Download example data (coordinates)"""

! git clone https://github.com/JAAAE/GSV_pano.git

"""# Read coordinates from the csv file, filter pano_id based on the date, and export the pano id to the csv file.

"""

from streetview import search_panoramas
import csv

# Open the csv file
with open('/content/GSV_pano/coordinates.csv', 'r') as file:
    # Create a csv reader
    reader = csv.reader(file)

    pano_ids_first = []

    # Iterate over each row in the csv
    for row in reader:
        # Extract latitude and longitude from the row
        lat, lon = row[0], row[1]

        # Perform panorama search
        panoramas = search_panoramas(lat=lat, lon=lon)

        # Filter panoramas based on csv date (e.g. after 2018)
        filtered_panoramas = [panorama for panorama in panoramas if panorama.date is not None and int(panorama.date.split('-')[0]) > 2019]

        # Extract the pano_id based on the filtered Google Street View (GSV) date
        if filtered_panoramas:
            pano_ids_first.append(filtered_panoramas[0].pano_id)

# Append the pano_ids as a new column in the existing csv file
with open('output_pano_id.csv', 'a', newline='') as csvfile:
    writer = csv.DictWriter(csvfile,fieldnames = ["pano_id"])
    writer.writeheader()
    writer = csv.writer(csvfile)

    # Write each pano_id in a new row as a separate column
    for pano_id in pano_ids_first:
        writer.writerow([pano_id])

"""# download panoramic imagery """

from streetview import get_panorama
import csv

# Open the csv file
with open('output_pano_id.csv', 'r') as file:
    # Create a csv reader
    reader = csv.reader(file)
    next(reader)
    # Iterate over each row in the csv
    for row in reader:
        # Extract the panorama ID from the row
        pano_id = row[0]  # Assuming the panorama ID is in the third column (index 2)
        print(pano_id)
        # Retrieve the panorama image
        image = get_panorama(pano_id=pano_id)

        # Save the image
        image.save(f"{pano_id}.jpg", "jpeg")